# 服务器配置
server:
  port: 8100
  application: spring-boot test
  env: dev
#  servlet:
#    context-path: /demo

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  profiles:
    include: database,redis
  zookeeper:
      serverPath: /system/config/server
      connectStr: 127.0.0.1:2181
      sessionTimeout: 60000
      connectTimeout: 60000
      reconnectTimes: 3

redis:
  shard:
      host:
        - 127.0.0.1
        - 127.0.0.1
      port:
        - 6379
        - 6379

