# 服务器配置
server:
  port: 8081
  context-path: /demo
  application: spring-boot test
  env: dev

spring:
  profiles:
    include: database,redis
  zookeeper:
      serverPath: /system/config/server
      connectStr: 127.0.0.1:2181
      sessionTimeout: 60000
      connectTimeout: 60000
      reconnectTimes: 3
  shard:
    redis:
      1:
        host: 127.0.0.1
        port: 6379
      2:
        host: 127.0.0.1
        port: 6380
